language: java
services:
  - docker
before_install:
- docker build -t katalonstudio/katalon .
- docker run -d --name katalonstudio katalonstudio/katalon /bin/bash
- docker ps -a
- docker run katalonstudio /bin/sh -c 'katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"'
script:
- docker run katalonstudio /bin/sh -c 'katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"'