language: java
services:
  - docker
before_install:
- docker pull katalonstudio/katalon
- docker run -d -p 127.0.0.1:80:4567 katalonstudio/katalon /bin/bash
- docker ps -a
- docker run -it katalonstudio/katalon /bin/sh -c "katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath='Test Suites/TS_RegressionTest'

script:
- katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"