language: java
services:
  - docker
before_install:
- docker pull katalonstudio/katalon
- docker run -d katalonstudio/katalon --name katalonstudio /bin/bash
- docker ps -a

script:
- docker exec -it katalonstudio /bin/sh -c "ls /katalon/katalon/script/"